# References:
    # https://openweathermap.org/weather-conditions

weather_codes = {
    200: "thunderstorm with light rain",
    201: "thunderstorm with rain",
    202: "thunderstorm with heavy rain",
    210: "light thunderstorm",
    211: "thunderstorm",
    212: "heavy thunderstorm",
    221: "ragged thunderstorm",
    230: "thunderstorm with light drizzle",
    231: "thunderstorm with drizzle",
    232: "thunderstorm with heavy drizzle",
    300: "light intensity drizzle",
    301: "drizzle",
    302: "heavy intensity drizzle",
    310: "light intensity drizzle rain",
    311: "drizzle rain",
    312: "heavy intensity drizzle rain",
    313: "shower rain and drizzle",
    314: "heavy shower rain and drizzle",
    321: "shower drizzle",
    500: "light rain",
    501: "moderate rain",
    502: "heavy intensity rain",
    503: "very heavy rain",
    504: "extreme rain",
    511: "freezing rain",
    520: "light intensity shower rain",
    521: "shower rain",
    522: "heavy intensity shower rain",
    531: "ragged shower rain",
    600: "light snow",
    601: "snow",
    602: "heavy snow",
    611: "sleet",
    612: "light shower sleet",
    613: "shower sleet",
    615: "light rain and snow",
    616: "rain and snow",
    620: "light shower snow",
    621: "shower snow",
    622: "heavy shower snow",
    701: "mist",
    711: "smoke",
    721: "haze",
    731: "sand/dust whirls",
    741: "fog",
    751: "sand",
    761: "dust",
    762: "volcanic ash",
    771: "squalls",
    781: "tornado",
    800: "clear sky",
    801: "few clouds: 11-25%",
    802: "scattered clouds: 25-50%",
    803: "broken clouds: 51-84%",
    804: "overcast clouds: 85-100%"
}
weather_translations = {
    "thunderstorm with light rain": "가벼운 비를 동반한 뇌우",
    "thunderstorm with rain": "비를 동반한 뇌우",
    "thunderstorm with heavy rain": "강한 비를 동반한 뇌우",
    "light thunderstorm": "약한 뇌우",
    "thunderstorm": "뇌우",
    "heavy thunderstorm": "강한 뇌우",
    "ragged thunderstorm": "불규칙한 뇌우",
    "thunderstorm with light drizzle": "가벼운 이슬비를 동반한 뇌우",
    "thunderstorm with drizzle": "이슬비를 동반한 뇌우",
    "thunderstorm with heavy drizzle": "강한 이슬비를 동반한 뇌우",
    "light intensity drizzle": "가벼운 이슬비",
    "drizzle": "이슬비",
    "heavy intensity drizzle": "강한 이슬비",
    "light intensity drizzle rain": "가벼운 비를 동반한 이슬비",
    "drizzle rain": "비를 동반한 이슬비",
    "heavy intensity drizzle rain": "강한 이슬비를 동반한 이슬비",
    "shower rain and drizzle": "소나기 및 이슬비",
    "heavy shower rain and drizzle": "강한 소나기 및 이슬비",
    "shower drizzle": "소나기 이슬비",
    "light rain": "약한 비",
    "moderate rain": "보통 비",
    "heavy intensity rain": "강한 비",
    "very heavy rain": "매우 강한 비",
    "extreme rain": "극심한 비",
    "freezing rain": "어는 비",
    "light intensity shower rain": "약한 소나기 비",
    "shower rain": "소나기 비",
    "heavy intensity shower rain": "강한 소나기 비",
    "ragged shower rain": "불규칙한 소나기 비",
    "light snow": "가벼운 눈",
    "snow": "눈",
    "heavy snow": "강한 눈",
    "sleet": "진눈깨비",
    "light shower sleet": "가벼운 소나기 진눈깨비",
    "shower sleet": "소나기 진눈깨비",
    "light rain and snow": "약한 비와 눈",
    "rain and snow": "비와 눈",
    "light shower snow": "가벼운 소나기 눈",
    "shower snow": "소나기 눈",
    "heavy shower snow": "강한 소나기 눈",
    "mist": "옅은 안개",
    "smoke": "연기",
    "haze": "안개",
    "sand/dust whirls": "모래/먼지 회오리",
    "fog": "안개",
    "sand": "모래",
    "dust": "먼지",
    "volcanic ash": "화산재",
    "squalls": "돌풍",
    "tornado": "토네이도",
    "clear sky": "맑은 하늘",
    "few clouds: 11-25%": "약간의 구름 (11-25%)",
    "scattered clouds: 25-50%": "드문 구름 (25-50%)",
    "broken clouds: 51-84%": "조각 구름 (51-84%)",
    "overcast clouds: 85-100%": "흐린 구름 (85-100%)"
}
